CREATE TABLE scms_delivery_history (
    id INT,
    project_code TEXT,
    pq_number TEXT,
    po_so_number TEXT,
    asn_dn_number TEXT,
    country TEXT,
    managed_by TEXT,
    fulfill_via TEXT,
    vendor_inco_term TEXT,
    shipment_mode TEXT,
    pq_first_sent_to_client_date TEXT,
    po_sent_to_vendor_date TEXT,
    scheduled_delivery_date TEXT,
    delivered_to_client_date TEXT,
    delivery_recorded_date TEXT,
    product_group TEXT,
    sub_classification TEXT,
    vendor TEXT,
    item_description TEXT,
    molecule_test_type TEXT,
    brand TEXT,
    dosage TEXT,
    dosage_form TEXT,
    unit_of_measure_per_pack INT,
    line_item_quantity INT,
    line_item_value NUMERIC(20, 2),
    pack_price NUMERIC(20, 2),
    unit_price NUMERIC(20, 2),
    manufacturing_site TEXT,
    first_line_designation TEXT,
    weight_kilograms TEXT,        -- Messy data, keep as TEXT for now
    freight_cost_usd TEXT,        -- Messy data, keep as TEXT for now
    line_item_insurance_usd NUMERIC(20, 2)
);